name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DIR: draft
      FILE: draft
 
    steps:

      - name: repo
        uses: actions/checkout@v4

      - name: texlive
        run: |
          sudo apt-get update
          sudo apt-get install texlive texlive-publishers texlive-science latexmk cm-super

      - name: latex
        working-directory: ${{env.DIR}}
        run: |
          pdflatex -interaction=nonstopmode ${{env.FILE}}
          if bibtex ${{env.FILE}}; then
            pdflatex -interaction=nonstopmode ${{env.FILE}}
            pdflatex -interaction=nonstopmode ${{env.FILE}}
          fi

      - name: push
        run: |
          mv draft/draft.pdf .
          if git show-ref --quiet remotes/origin/build; then
            git push -d origin build
          fi
          git checkout -b build
          git add draft.pdf
          git commit -m 'build'
          git push
